### ISSUE TITLE
Upload .md files to github instead/as well

### ISSUE THREAD

**Issue by WnndGws** [LMLAus/STAT1006#1]
Are you able to upload the markdown files? This would help in several ways:

1) Unix tools can be used on text files (eg grep, awk, sed etc)
2) People can copy the info and suggest changes for you, rather than you needing to make the changes yourself
3) People will be able to edit the info for their purposes

**Comment by LMLAus** [comment]
This is now complete for COMP1005, and is halfway complete for STAT1006, which will be completed in the next few days.

I have only done this for the main cheat sheets as it requires reformatting the originals, however I will do this for all other uploads in future. 

Thank you for the feedback.

Edit: Completed for STAT1006, but I have left the original pdf up as the readability is better without the code chunks.

**Comment by WnndGws** [comment]
Because PDFs were created in LaTeX, they can be searched by ripgrep-all (on arch)
